import ArticleCard from './components/ArticleCard'
import Sidebar from './components/Sidebar'
import { generateSampleArticles } from './data/sampleArticles'

export default function Home() {
  const articles = generateSampleArticles()

  return (
    <div className="max-w-7xl mx-auto">
      {/* Hero Section */}
      <section className="mb-12">
        <div className="bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl p-8 text-white">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            AI-Powered News, Updated Daily
          </h1>
          <p className="text-xl mb-6">
            Get the latest technology, business, and AI news generated by artificial intelligence.
            Fresh content published automatically every day.
          </p>
          <div className="flex space-x-4">
            <button className="bg-white text-blue-600 font-semibold px-6 py-3 rounded-lg hover:bg-gray-100 transition">
              Explore Articles
            </button>
            <button className="bg-transparent border-2 border-white text-white font-semibold px-6 py-3 rounded-lg hover:bg-white/10 transition">
              How It Works
            </button>
          </div>
        </div>
      </section>

      <div className="flex flex-col lg:flex-row gap-8">
        {/* Main Content */}
        <div className="lg:w-2/3">
          {/* Featured Articles */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold mb-6 text-gray-900">Featured Today</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {articles.slice(0, 4).map((article) => (
                <ArticleCard key={article.id} article={article} featured />
              ))}
            </div>
          </section>

          {/* In-Article Ad */}
          <div className="my-12">
            <div className="ad-container ad-unit">
              <p className="text-sm text-gray-500">Advertisement</p>
              <div className="text-gray-400">In-Article Ad (300x250)</div>
            </div>
          </div>

          {/* Latest Articles */}
          <section>
            <h2 className="text-3xl font-bold mb-6 text-gray-900">Latest News</h2>
            <div className="space-y-6">
              {articles.slice(4).map((article) => (
                <ArticleCard key={article.id} article={article} />
              ))}
            </div>
          </section>

          {/* Pagination */}
          <div className="mt-12 flex justify-center">
            <nav className="flex space-x-2">
              <button className="px-4 py-2 bg-blue-600 text-white rounded-lg">1</button>
              <button className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300">2</button>
              <button className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300">3</button>
              <button className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300">Next →</button>
            </nav>
          </div>
        </div>

        {/* Sidebar */}
        <div className="lg:w-1/3">
          <Sidebar />
        </div>
      </div>

      {/* Bottom Ad */}
      <div className="mt-16">
        <div className="ad-container ad-unit">
          <p className="text-sm text-gray-500">Advertisement</p>
          <div className="text-gray-400">Bottom Banner Ad (728x90)</div>
        </div>
      </div>
    </div>
  )
}